import React from 'react';
import {AbsoluteFill,Audio,Composition,Sequence,interpolate,registerRoot,spring,staticFile,useCurrentFrame} from 'remotion';
const C={ink:'#29251e',cream:'#fff5de',orange:'#ed815d',lime:'#d8ec85',sage:'#8b9467'};
const pop=(f,d=0)=>spring({frame:Math.max(0,f-d),fps:30,config:{damping:16,stiffness:150}});
const label={fontSize:25,fontWeight:700,letterSpacing:3};
const title={fontSize:116,fontWeight:900,lineHeight:.97,letterSpacing:-6};
function Word({children,delay=0,color}){const f=useCurrentFrame();return <div style={{color,opacity:f<delay?0:1,transform:`translateY(${(1-pop(f,delay))*55}px) scale(${.9+.1*pop(f,delay)})`,transformOrigin:'left center'}}>{children}</div>}
function Shell({children,bg=C.cream,color=C.ink,kicker}){const f=useCurrentFrame();return <AbsoluteFill style={{background:bg,color,padding:'285px 105px 340px',fontFamily:'Arial',overflow:'hidden'}}><div style={{position:'absolute',right:-160,top:320,width:510,height:510,border:`2px solid ${color}`,borderRadius:'50%',opacity:.12,transform:`translateY(${Math.sin(f/30)*25}px)`}}/><div style={{...label,marginBottom:60}}>{kicker}</div>{children}</AbsoluteFill>}
function Hook(){const f=useCurrentFrame();return <Shell bg={C.ink} color={C.cream} kicker="DIGITAL MEDIA / ROCHESTER"><div style={{...title,fontSize:114,marginTop:55}}><Word>“Definitely</Word><Word delay={6} color={C.lime}>double</Word><Word delay={12} color={C.lime}>major”</Word></div><div style={{fontSize:32,lineHeight:1.35,marginTop:45}}>One graduate’s do-over.<br/><span style={{fontSize:24,color:'#cbc2b1'}}>Exact review excerpt</span></div><div style={{position:'absolute',top:1130,left:110,transform:`rotate(${-7+2*Math.sin(f/25)}deg) scale(${.92+.08*pop(f,20)})`,background:C.orange,padding:'24px 32px',color:C.ink,border:'3px solid '+C.cream,fontWeight:900,fontSize:44}}>WHY? →</div><div style={{position:'absolute',top:1250,right:140,width:180,height:180,borderRadius:'50%',background:C.lime,color:C.ink,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',transform:`rotate(${8*Math.sin(f/35)}deg)`}}><strong style={{fontSize:60}}>3/5</strong><span style={{fontSize:18,fontWeight:700}}>THEIR RATING</span></div></Shell>}
function Projects(){const f=useCurrentFrame();return <Shell kicker="01 / THE COURSEWORK"><div style={title}><Word>Project</Word><Word delay={5}>after</Word><Word delay={10} color='#bd4f32'>project.</Word></div><div style={{fontSize:31,marginTop:32}}>Their description of the major.</div><div style={{position:'relative',marginTop:75,height:510}}>{['PLAN','DESIGN','BUILD'].map((t,i)=><div key={t} style={{position:'absolute',left:i*75,top:i*165,width:520,height:150,background:[C.sage,C.orange,C.ink][i],color:i===0?C.cream:i===1?C.ink:C.lime,border:'3px solid '+C.ink,padding:30,fontSize:49,fontWeight:900,boxShadow:'9px 9px 0 #29251e22',transform:`translateX(${(1-pop(f,10+i*9))*650}px) rotate(${[-5,3,-3][i]}deg)`}}><span style={{fontSize:22,marginRight:24}}>0{i+1}</span>{t}</div>)}</div></Shell>}
function Team(){const f=useCurrentFrame();const points=[[105,160],[520,160],[310,410]];return <Shell bg={C.orange} kicker="02 / THE BIGGEST CHALLENGE"><div style={{fontSize:65,fontWeight:700,letterSpacing:-3}}>The hard part?</div><div style={{...title,fontSize:142,marginTop:15}}><Word delay={5}>THE TEAM.</Word></div><svg width="780" height="570" viewBox="0 0 780 570" style={{marginTop:55,overflow:'visible'}}><path d="M 195 240 L 610 240 L 400 490 Z" fill="none" stroke={C.ink} strokeWidth="5" strokeDasharray="14 12" strokeDashoffset={-f*2}/>{points.map(([x,y],i)=><g key={i} transform={`translate(${x},${y+Math.sin(f/10+i)*9})`}><rect x="-25" y="-45" width="215" height="175" rx="20" fill={i===1?C.ink:C.cream} stroke={C.ink} strokeWidth="4"/><circle cx="80" cy="10" r="28" fill={i===1?C.lime:C.sage}/><path d="M30 88 Q80 20 130 88" fill={i===1?C.lime:C.sage}/></g>)}</svg><div style={{fontSize:32,lineHeight:1.4,marginTop:12}}>Learning to work with others.<br/>Learning to stay flexible.</div></Shell>}
function Niche(){const f=useCurrentFrame();return <Shell bg={C.ink} color={C.cream} kicker="03 / THE STRETCH"><div style={title}><Word>Outside</Word><Word delay={5}>your</Word><Word delay={10} color={C.lime}>comfort zone.</Word></div><div style={{fontSize:31,lineHeight:1.4,marginTop:38}}>Projects can push you<br/>beyond your chosen niche.</div><div style={{marginTop:65,display:'flex',flexDirection:'column',gap:20}}>{['GRAPHIC DESIGN','UX / UI','CODING'].map((t,i)=><div key={t} style={{fontSize:40,fontWeight:900,border:`2px solid ${C.lime}`,color:C.lime,padding:'20px 28px',transform:`translateX(${(1-pop(f,12+i*10))*800}px)`,display:'flex',justifyContent:'space-between'}}>{t}<span>↗</span></div>)}</div></Shell>}
function Advice(){return <Shell bg={C.lime} kicker="04 / WHAT THEY’D CHANGE"><div style={{...title,fontSize:108}}><Word>Double</Word><Word delay={5}>major.</Word><div style={{fontFamily:'Georgia',fontSize:61,fontWeight:400,margin:'25px 0'}}>or</div><Word delay={12}>Make it</Word><Word delay={17}>a minor.</Word></div><div style={{fontSize:32,lineHeight:1.4,marginTop:55}}>Their reason: the core skills<br/>connect to other fields.</div><div style={{fontSize:24,marginTop:32}}>Paraphrased from this graduate’s review.</div></Shell>}
function Close(){return <Shell bg={C.ink} color={C.cream} kicker="YOUR TURN"><div style={{...title,fontSize:108}}><Word>What would</Word><Word delay={4}>YOU pair</Word><Word delay={8} color={C.orange}>it with?</Word></div><div style={{fontSize:35,marginTop:65}}>Drop your second major ↓</div><div style={{fontSize:29,lineHeight:1.5,marginTop:60,color:'#cbc2b1'}}>Read & share student reviews<br/>on RateMyDegree.</div></Shell>}
function Reel(){const f=useCurrentFrame();const starts=[0,90,180,285,390,510];const lengths=[90,90,105,105,120,120];const scenes=[Hook,Projects,Team,Niche,Advice,Close];const dark=f<90||(f>=285&&f<390)||f>=510;return <AbsoluteFill><Audio src={staticFile('dms-pulse.wav')} volume={.45}/>{scenes.map((S,i)=><Sequence key={i} from={starts[i]} durationInFrames={lengths[i]}><S/></Sequence>)}<div style={{position:'absolute',top:155,left:105,right:140,display:'flex',justifyContent:'space-between',alignItems:'center',color:dark?C.cream:C.ink,fontFamily:'Arial'}}><span style={{fontSize:29,fontWeight:900}}>RateMyDegree<span style={{color:dark?C.lime:'#bd4f32'}}> ●</span></span><span style={{fontSize:22}}>STUDENT VOICE / 003</span></div><div style={{position:'absolute',bottom:280,left:105,right:145,color:dark?'#cbc2b1':C.ink,fontFamily:'Arial',fontSize:23,lineHeight:1.5}}>University of Rochester · Graduate<br/>Digital Communication & Media/Multimedia<br/><span style={{fontSize:20}}>One person’s experience · October 2026</span></div><div style={{position:'absolute',bottom:238,left:105,right:145,display:'flex',gap:10}}>{starts.map((s,i)=><div key={s} style={{height:5,flex:1,background:dark?'#605a4d':'#29251e33'}}><div style={{height:'100%',width:`${interpolate(f,[s,s+lengths[i]],[0,100],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}%`,background:dark?C.lime:C.ink}}/></div>)}</div></AbsoluteFill>}
registerRoot(()=> <Composition id="RochesterMedia" component={Reel} durationInFrames={630} fps={30} width={1080} height={1920}/>);

