import React from 'react';
import {AbsoluteFill,Composition,Sequence,interpolate,registerRoot,spring,useCurrentFrame,useVideoConfig} from 'remotion';
const ink='#433422',paper='#fdf6e3',sage='#8b9467',rust='#c36b4e';
const source={source:'User-provided review screenshot, September 2026',school:'University of Rochester',major:'Computer Science',quote:'How hard recruiting is but also how rewarding it could be.'};
const Serif=({children,style={}})=><div style={{fontFamily:'Georgia',letterSpacing:-3,lineHeight:1.08,...style}}>{children}</div>;
function Scene({children,dark=false}){const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:200}});return <AbsoluteFill style={{background:dark?ink:paper,color:dark?paper:ink,padding:'270px 100px 320px',justifyContent:'center',opacity:interpolate(f,[0,8],[0,1],{extrapolateRight:'clamp'})}}><div style={{transform:`translateY(${(1-p)*45}px)`}}>{children}</div></AbsoluteFill>}
function Reel(){const f=useCurrentFrame();return <AbsoluteFill style={{background:paper,fontFamily:'Arial',color:ink}}>
<Sequence from={0} durationInFrames={120}><Scene><div style={{fontSize:26,letterSpacing:5,marginBottom:52}}>COMPUTER SCIENCE / STUDENT LIFE</div><Serif style={{fontSize:110}}>Let’s talk<br/><span style={{color:rust}}>CS<br/>recruiting.</span></Serif><div style={{width:130,height:8,background:sage,marginTop:48}}/><div style={{fontSize:34,marginTop:42,lineHeight:1.4}}>One Rochester student’s experience.</div></Scene></Sequence>
<Sequence from={120} durationInFrames={270}><Scene><div style={{display:'inline-block',background:sage,color:paper,borderRadius:40,padding:'16px 26px',fontSize:27,marginBottom:36}}>STUDENT VOICE / 002</div><div style={{fontSize:30,marginBottom:44}}>University of Rochester · Computer Science</div><div style={{background:'#fffefb',border:`3px solid ${ink}`,borderRadius:32,padding:'38px 46px 48px',boxShadow:`14px 16px 0 ${sage}`}}><Serif style={{fontSize:116,color:rust,height:85}}>“</Serif><Serif style={{fontSize:67,letterSpacing:-1.6,lineHeight:1.19}}>{source.quote}</Serif><div style={{fontSize:25,marginTop:35,color:'#716451'}}>— Current student · What surprised me</div></div><div style={{fontSize:25,marginTop:42}}>Overall satisfaction: 4 / 5 · This student’s rating</div></Scene></Sequence>
<Sequence from={390} durationInFrames={150}><Scene dark><div style={{fontSize:27,letterSpacing:4,marginBottom:48,color:'#c8cea9'}}>YOUR EXPERIENCE MATTERS</div><Serif style={{fontSize:99}}>When did<br/>you start<br/><span style={{color:'#e5a78f'}}>recruiting?</span></Serif><div style={{marginTop:58,fontSize:35,lineHeight:1.5}}>Share your experience in the comments.</div><div style={{fontSize:28,marginTop:28,color:'#d8d2c5'}}>Read & share degree reviews<br/>on RateMyDegree.</div></Scene></Sequence>
<div style={{position:'absolute',top:160,left:100,right:130,display:'flex',alignItems:'center',gap:16,color:f>=390?paper:ink}}><div style={{height:34,width:34,background:rust,borderRadius:'50%'}}/><span style={{fontFamily:'Georgia',fontSize:36,fontWeight:700}}>RateMyDegree</span></div>
<div style={{position:'absolute',bottom:265,left:100,right:130,height:4,background:f>=390?'#6b5c49':'#ded5bc'}}><div style={{height:'100%',width:`${100*f/539}%`,background:rust}}/></div>
</AbsoluteFill>}
registerRoot(()=> <Composition id="RochesterReview" component={Reel} durationInFrames={540} fps={30} width={1080} height={1920}/>);
